### ISSUE TITLE
A few questions:)

### ISSUE THREAD

**Issue by fourstepper** [bbrks/chrome-gruvbox#4]
Hello, is the project still maintained? How would I go about editing the theme and applying the edited version?

Thanks!

**Comment by bbrks** [comment]
Hi @fourstepper ,

I don't use a Chrome-based browser any more, so haven't look at this in a while.

As far as I remember, you can load an unpacked version of the manifest by enabling some options in Chrome:

https://developer.chrome.com/extensions/getstarted#manifest

**Comment by fourstepper** [comment]
Do you use Firefox nowadays?

**Comment by bbrks** [comment]
Yep! Switched a few years ago (shortly after creating this theme actually)

**Comment by fourstepper** [comment]
Nice @bbrks
